---
kind: pipeline
name: build

steps:
  - name: build
    pull: always
    image: golang
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o apitest .
    environment:
      GO111MODULE: on

  - name: publish
    pull: always
    image: plugins/docker
    settings:
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/lm93129/drone_yapi_test
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      status:
        - success
